[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.blind:get_type() == 'Boss' then"
position = "at"
payload = '''
if G.GAME.round_resets.blind_choices.Boss == "bl_boingular_executioner_blind" then
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "G.shop_jokers:emplace(create_card_for_shop(G.shop_jokers))"
position = "after"
payload = '''
check_for_unlock({type = 'shop_joker', area = G.shop_jokers})
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "if #G.hand.highlighted <= 0 or G.GAME.blind.block_play or #G.hand.highlighted > 5 then"
position = "at"
payload = '''
if #G.hand.highlighted <= 0 or G.GAME.blind.block_play then
'''
match_indent = true