[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.blind:get_type() == 'Boss' then"
position = "at"
payload = '''
if G.GAME.round_resets.blind_choices.Boss == "bl_boingular_executioner_blind" then
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "G.shop_jokers:emplace(create_card_for_shop(G.shop_jokers))"
position = "after"
payload = '''
check_for_unlock({type = 'shop_joker', area = G.shop_jokers})
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "if #G.hand.highlighted <= 0 or G.GAME.blind.block_play or #G.hand.highlighted > 5 then"
position = "at"
payload = '''
if #G.hand.highlighted <= 0 or G.GAME.blind.block_play then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "enhanced = G.C.SECONDARY_SET.Enhanced"
position = "at"
payload = '''
enhanced = G.C.SECONDARY_SET.Enhanced,
eternal = G.C.ETERNAL
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "conf.lua"
pattern = "t.title = 'Balatro'"
position = "at"
payload = '''
t.title = 'boingulatro!'
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "13*SC_scale,"
position = "at"
payload = '''
19*SC_scale, 
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '13*SC_scale*(G.ASSET_ATLAS["balatro"].py/G.ASSET_ATLAS["balatro"].px),'
position = "at"
payload = '''
19*SC_scale*(G.ASSET_ATLAS["balatro"].py/G.ASSET_ATLAS["balatro"].px),
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "G.title_top.T.x = G.TILE_W/2 - G.title_top.T.w/2"
position = "at"
payload = '''
G.title_top.T.x = G.TILE_W/2 - G.title_top.T.w/2 + G.TILE_W*0.165
'''
times = 2
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "G.SPLASH_LOGO:define_draw_steps({{"
position = "before"
payload = '''
G.SPLASH_LOGO:set_alignment({
    major = G.title_top,
    type = 'cm',
    bond = 'Strong',
    offset = {x=-G.TILE_W*0.165,y=0}
})
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "local replace_card = Card(self.title_top.T.x, self.title_top.T.y, 1.2*G.CARD_W*SC_scale, 1.2*G.CARD_H*SC_scale, G.P_CARDS.S_A, G.P_CENTERS.c_base)"
position = "at"
payload = '''
local replace_card = Card(self.title_top.T.x, self.title_top.T.y, 1.2*0.65*G.CARD_W*SC_scale, 1.2*0.65*G.CARD_H*SC_scale, G.P_CARDS.H_A, G.P_CENTERS.c_base)
local boingular_replace_card = math.random()
if (boingular_replace_card < 0.05) then
    replace_card:set_edition("e_boingular_green")
end
'''
match_indent = true