[manifest]
version = "1.0.0"
priority = 0

[[patches]]

[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.blind:get_type() == 'Boss' then"
position = "at"
payload = '''
if G.GAME.round_resets.blind_choices.Boss == "bl_boingular_executioner_blind" then
'''
match_indent = true
times = 1